### ISSUE TITLE
installation using pip fails

### ISSUE THREAD

**Issue by johnyf** [netom/satispy#1]
with the message:
```
pip install satispy
Downloading/unpacking satispy
  Could not find a version that satisfies the requirement satispy (from versions: 1.0a4)
Cleaning up...
No distributions matching the version for satispy
Storing complete log in /Users/user/.pip/pip.log
```
and after reading [this](http://stackoverflow.com/questions/18230956/could-not-find-a-version-that-satisfies-the-requirement-pytz) it might be the case that changing the version numbering to numbers-only may avoid this issue.

**Comment by netom** [comment]
Fixed. Sorry for the terrible response time. :)

**Comment by netom** [comment]
,
