### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by yberman** [netom/satispy#11]
I use satispy heavily, but I am switching to 3 and I was wondering if you could make it compatible?

https://docs.python.org/3/howto/pyporting.html

If not, would you be interested in having a patch written that does?

**Comment by netom** [comment]
Thank you for the report @yberman. I have little time nowdays to properly take care of the library, but I'll do my best to port pyicap to Python 3 ASAP. This could mean months, so PRs are very welcome.

**Comment by netom** [comment]
...I mean satispy of course. PyICAP is an other library. :D

**Comment by netom** [comment]
Well, it took a while, but finally it's ready. I also included a .travis.yml for automatic testing.
