### ISSUE TITLE
Error: "system cannot find the path specified"

### ISSUE THREAD

**Issue by Abdusha** [netom/satispy#14]
Halo, I'm new in python. I try using satispy with example code but I get this error "system cannot find the path specified". can you help me? 

------------------------------------------------------------
I'm using this code:
`from satispy import Variable, Cnf
from satispy.solver import Minisat

v1 = Variable('v1')
v2 = Variable('v2')
v3 = Variable('v3')

exp = v1 & v2 | v3

solver = Minisat()

solution = solver.solve(exp)

print solution

if solution.success:
    print "Found a solution:"
    print v1, solution[v1]
    print v2, solution[v2]
    print v3, solution[v3]
else:
    print "The expression cannot be satisfied"`

the output is:
The system cannot find the path specified.
<satispy.solution.Solution object at 0x064B14D0>
The expression cannot be satisfied

**Comment by netom** [comment]
Hello, and thanks for choosing Satispy :)

What OS are you using? Also, make sure minisat solver is instsllef (does
the command "minisat" work?)

Cheers,

Tamas

2019. febr. 13., Sze 5:46 dátummal Abdurrahman Shaleh <
notifications@github.com> ezt írta:

**Comment by Abdusha** [comment]
I'm using windows 7

**Comment by netom** [comment]
Please check wether minisat is installed (check if the command "minisat" works).
